"""Constants for the asyncua integration."""

DOMAIN = "asyncua"

"""Constant required for asnycua hub"""
CONF_HUB_ID = "name"
CONF_HUB_MANUFACTURER = "manufacturer"
CONF_HUB_MODEL = "model"
CONF_HUB_SCAN_INTERVAL = "scan_interval"
CONF_HUB_URL = "url"
CONF_HUB_USERNAME = "username"
CONF_HUB_PASSWORD = "password"

"""Constant required for opcua entities"""
CONF_NODES = "nodes"
CONF_NODE_DEVICE_CLASS = "device_class"
CONF_NODE_HUB = "hub"
CONF_NODE_ID = "nodeid"
CONF_NODE_NAME = "name"
CONF_NODE_STATE_CLASS = "state_class"
CONF_NODE_UNIQUE_ID = "unique_id"
CONF_NODE_UNIT_OF_MEASUREMENT = "unit_of_measurement"

"""Constant required for opcua entities identified as a contactor or switch"""
CONF_NODE_SWITCH_DI = "nodeid_switch_di"

"""COnstant required to set values"""
ATTR_NODE_HUB = "hub"
ATTR_NODE_ID = "nodeid"
ATTR_VALUE = "value"
SERVICE_SET_VALUE = "set_value"

"""Constants for cover entities"""
CONF_TRAVELLING_TIME_DOWN = "travelling_time_down"
CONF_TRAVELLING_TIME_UP = "travelling_time_up"
CONF_OPEN_NODEID = "open_nodeid"
CONF_CLOSE_NODEID = "close_nodeid"
CONF_STOP_NODEID = "stop_nodeid"
CONF_FULLY_OPEN_NODEID = "fully_open_nodeid"
CONF_FULLY_CLOSED_NODEID = "fully_closed_nodeid"
